In [49]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)

In [50]:
df = pd.read_csv('nba_player_averages_2026.csv')
df.head()

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season
0,A.J. Lawson,TOR,25.0,24,9.4,1.4,3.3,0.436,0.8,1.9,0.422,0.6,0.8,0.778,0.4,1.4,1.8,0.3,0.3,0.5,0.2,1.1,4.2,2026
1,AJ Green,MIL,26.0,78,29.1,3.4,7.9,0.424,3.0,7.1,0.419,0.7,0.8,0.855,0.4,2.4,2.7,1.9,1.0,0.5,0.1,2.3,10.4,2026
2,AJ Johnson,DAL,21.0,48,9.4,1.2,3.7,0.324,0.3,1.2,0.211,0.7,0.8,0.850,0.3,0.9,1.1,1.0,0.6,0.2,0.1,0.6,3.3,2026
3,Aaron Gordon,DEN,30.0,36,27.9,5.5,11.1,0.497,1.7,4.4,0.389,3.5,4.5,0.767,1.4,4.4,5.8,2.7,1.1,0.6,0.3,1.7,16.2,2026
4,Aaron Holiday,HOU,29.0,57,13.7,1.8,4.4,0.417,1.2,3.0,0.394,0.6,0.7,0.854,0.2,0.8,1.0,1.1,0.7,0.5,0.1,1.3,5.5,2026

In [51]:
df[df['Player'].isin(['Cade Cunningham', 'Jalen Johnson', 'Jayson Tatum'])]

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season
71,Cade Cunningham,DET,24.0,64,33.9,8.6,18.6,0.461,2.0,5.7,0.342,4.8,6.0,0.812,0.9,4.7,5.5,9.9,3.7,1.4,0.8,3.1,23.9,2026
234,Jalen Johnson,ATL,24.0,72,35.2,8.3,17.1,0.489,1.7,4.7,0.352,4.2,5.3,0.788,1.4,8.9,10.3,7.9,3.4,1.2,0.4,2.1,22.5,2026
266,Jayson Tatum,BOS,28.0,16,32.6,7.4,17.9,0.411,2.9,8.9,0.329,4.1,4.9,0.823,0.5,9.5,10.0,5.3,2.4,1.4,0.2,1.6,21.8,2026

In [52]:
px.histogram(df, x='PTS', nbins=10, title='Distribution of Points per Game', labels={'PTS': 'Points per Game'})

In [53]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Points vs Field Goal Percentage', 'Points vs Free Throw Percentage'))

fig.add_trace(
    go.Scatter(x=df['PTS'], y=df['FG%'], mode='markers', text=df['Player'], name='Field Goal %'),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=df['PTS'], y=df['FT%'], mode='markers', text=df['Player'], name='Free Throw %'),
    row=1, col=2
)

fig.update_layout(title='Points vs Shooting Percentages')

fig.show()

In [54]:
adp_df = pd.read_csv('adp_2026_27.csv')
adp_df.head()

   ESPN_ADP_Rank                   Player Team Positions
0              1             Nikola Jokic  DEN         C
1              2  Shai Gilgeous-Alexander  OKC        PG
2              3        Victor Wembanyama  SAS         C
3              4              Luka Doncic  LAL     PG,SG
4              5    Giannis Antetokounmpo  MIA      PF,C

In [55]:
df = df.merge(adp_df, on=['Player', 'Team'], how='left')
df.rename(columns={'ESPN_ADP_Rank': 'ADP'}, inplace=True)
df.head()

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
0,A.J. Lawson,TOR,25.0,24,9.4,1.4,3.3,0.436,0.8,1.9,0.422,0.6,0.8,0.778,0.4,1.4,1.8,0.3,0.3,0.5,0.2,1.1,4.2,2026,NaN,NaN
1,AJ Green,MIL,26.0,78,29.1,3.4,7.9,0.424,3.0,7.1,0.419,0.7,0.8,0.855,0.4,2.4,2.7,1.9,1.0,0.5,0.1,2.3,10.4,2026,NaN,NaN
2,AJ Johnson,DAL,21.0,48,9.4,1.2,3.7,0.324,0.3,1.2,0.211,0.7,0.8,0.850,0.3,0.9,1.1,1.0,0.6,0.2,0.1,0.6,3.3,2026,NaN,NaN
3,Aaron Gordon,DEN,30.0,36,27.9,5.5,11.1,0.497,1.7,4.4,0.389,3.5,4.5,0.767,1.4,4.4,5.8,2.7,1.1,0.6,0.3,1.7,16.2,2026,113.0,"PF,C"
4,Aaron Holiday,HOU,29.0,57,13.7,1.8,4.4,0.417,1.2,3.0,0.394,0.6,0.7,0.854,0.2,0.8,1.0,1.1,0.7,0.5,0.1,1.3,5.5,2026,NaN,NaN

In [56]:
df.sort_values(by='ADP', inplace=True)
df.head(50)

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
501,Shai Gilgeous-Alexander,OKC,27.0,68,33.2,10.8,19.4,0.553,1.7,4.4,0.386,7.9,9.0,0.879,0.6,3.7,4.3,6.6,2.2,1.4,0.8,2.0,31.1,2026,2.0,PG
559,Victor Wembanyama,SAS,22.0,64,29.2,8.6,16.9,0.512,1.9,5.5,0.349,5.8,7.0,0.827,2.0,9.5,11.5,3.1,2.4,1.0,3.1,2.4,25.0,2026,3.0,C
31,Anthony Edwards,MIN,24.0,61,35.0,9.9,20.2,0.489,3.4,8.4,0.399,5.7,7.2,0.796,0.6,4.4,5.0,3.7,2.9,1.4,0.8,1.9,28.8,2026,6.0,"PG,SF,SG"
71,Cade Cunningham,DET,24.0,64,33.9,8.6,18.6,0.461,2.0,5.7,0.342,4.8,6.0,0.812,0.9,4.7,5.5,9.9,3.7,1.4,0.8,3.1,23.9,2026,7.0,"PG,SG"
266,Jayson Tatum,BOS,28.0,16,32.6,7.4,17.9,0.411,2.9,8.9,0.329,4.1,4.9,0.823,0.5,9.5,10.0,5.3,2.4,1.4,0.2,1.6,21.8,2026,8.0,"SF,PF"
30,Anthony Davis,WAS,33.0,20,31.3,8.5,16.7,0.506,0.5,1.9,0.270,3.0,4.1,0.728,3.1,8.0,11.1,2.8,2.1,1.1,1.7,2.1,20.4,2026,9.0,"PF,C"
317,Karl-Anthony Towns,NYK,30.0,75,31.0,6.9,13.8,0.501,1.5,4.1,0.368,4.8,5.5,0.858,3.1,8.7,11.9,3.0,2.5,0.9,0.5,3.4,20.1,2026,11.0,"PF,C"
245,James Harden,CLE,36.0,70,34.8,7.0,16.0,0.434,3.1,8.2,0.375,6.6,7.5,0.884,0.6,4.2,4.8,8.0,3.5,1.1,0.4,2.0,23.6,2026,12.0,"PG,SG"
554,Tyrese Maxey,PHI,25.0,70,38.0,9.9,21.4,0.462,3.1,8.6,0.367,5.3,6.0,0.892,0.3,3.8,4.1,6.6,2.4,1.9,0.8,2.2,28.3,2026,13.0,"PG,SG"
151,Domantas Sabonis,SAC,30.0,19,29.7,6.3,11.6,0.543,0.3,1.4,0.185,2.9,4.1,0.727,3.4,8.0,11.4,4.1,2.7,0.9,0.2,3.5,15.8,2026,15.0,"C,PF"
21,Amen Thompson,HOU,23.0,79,37.4,7.1,13.2,0.534,0.3,1.5,0.216,3.8,4.9,0.779,3.0,4.8,7.8,5.3,2.4,1.5,0.6,2.2,18.3,2026,16.0,"PG,SF,SG"
509,Stephen Curry,GSW,38.0,43,30.9,8.7,18.6,0.468,4.4,11.3,0.393,4.7,5.1,0.923,0.4,3.2,3.6,4.7,2.8,1.1,0.4,1.7,26.6,2026,18.0,PG
231,Jalen Brunson,NYK,29.0,74,35.0,9.3,19.9,0.467,2.6,7.1,0.369,4.8,5.7,0.841,0.4,2.9,3.3,6.8,2.4,0.8,0.1,2.3,26.0,2026,19.0,PG
531,Trae Young,WAS,27.0,15,25.6,5.4,11.8,0.458,1.8,5.3,0.338,5.3,6.5,0.825,0.3,1.7,2.0,8.0,2.6,0.9,0.1,2.2,17.9,2026,20.0,PG
154,Donovan Mitchell,CLE,29.0,70,33.5,9.7,20.0,0.483,3.2,8.8,0.364,5.3,6.1,0.865,0.7,3.8,4.5,5.7,2.8,1.5,0.3,2.3,27.9,2026,21.0,"PG,SG"
455,Pascal Siakam,IND,32.0,62,33.2,9.0,18.6,0.484,1.7,4.7,0.358,4.2,6.1,0.693,1.4,5.2,6.6,3.8,2.2,1.1,0.4,2.4,24.0,2026,22.0,"C,PF,SF"
107,Cooper Flagg,DAL,19.0,70,33.5,8.0,17.1,0.468,1.0,3.5,0.295,4.0,4.9,0.827,1.2,5.4,6.7,4.5,2.3,1.2,0.9,2.0,21.0,2026,23.0,"PF,SF,SG"
333,Kevin Durant,HOU,37.0,78,36.4,9.2,17.6,0.520,2.4,5.8,0.413,5.2,6.0,0.874,0.5,4.9,5.5,4.8,3.2,0.8,0.9,1.8,26.0,2026,24.0,"PF,SF,SG"
496,Scottie Barnes,TOR,24.0,80,33.5,7.1,14.0,0.507,0.9,2.8,0.304,3.0,3.7,0.815,1.9,5.6,7.5,5.9,2.6,1.4,1.5,2.6,18.1,2026,25.0,"C,PF,SF,SG"
39,Bam Adebayo,MIA,28.0,73,32.4,6.9,15.7,0.442,1.7,5.5,0.318,4.5,5.8,0.778,2.0,8.0,10.0,3.2,1.6,1.2,0.7,1.7,20.1,2026,26.0,"C,PF"
299,Josh Giddey,CHI,23.0,54,32.1,5.9,13.3,0.448,1.9,5.2,0.364,3.2,4.2,0.763,1.2,7.1,8.3,9.1,3.6,1.0,0.5,1.7,17.0,2026,27.0,"PG,SG,SF"
239,Jalen Williams,OKC,25.0,33,28.4,6.5,13.5,0.484,0.7,2.3,0.299,3.3,3.9,0.837,0.8,3.8,4.6,5.5,1.9,1.2,0.3,2.0,17.1,2026,28.0,"PF,SF,SG"
19,Alperen Sengun,HOU,23.0,72,33.3,8.1,15.6,0.519,0.6,1.8,0.305,3.6,5.2,0.691,3.0,5.9,8.9,6.2,3.2,1.2,1.1,3.3,20.4,2026,30.0,"C,PF"
177,Evan Mobley,CLE,25.0,65,31.9,7.2,13.2,0.546,1.0,3.2,0.297,2.8,4.6,0.606,2.4,6.6,9.0,3.6,1.9,0.7,1.7,2.4,18.2,2026,31.0,"PF,C"
234,Jalen Johnson,ATL,24.0,72,35.2,8.3,17.1,0.489,1.7,4.7,0.352,4.2,5.3,0.788,1.4,8.9,10.3,7.9,3.4,1.2,0.4,2.1,22.5,2026,32.0,"PF,SF"
242,Jamal Murray,DEN,29.0,75,35.4,8.8,18.1,0.483,3.3,7.5,0.435,4.6,5.2,0.887,0.4,4.0,4.4,7.1,2.3,0.9,0.4,1.7,25.4,2026,33.0,PG
454,Paolo Banchero,ORL,23.0,72,34.7,7.3,16.0,0.459,1.2,3.8,0.305,6.3,8.2,0.775,1.2,7.2,8.4,5.2,3.1,0.7,0.6,2.0,22.2,2026,34.0,"PF,SF"
214,Ivica Zubac,IND,29.0,48,30.1,6.0,10.0,0.598,0.0,0.0,0.000,2.1,3.0,0.711,3.4,7.2,10.6,2.2,1.8,0.4,0.8,2.3,14.1,2026,35.0,C
130,De'Aaron Fox,SAS,28.0,72,31.0,7.1,14.5,0.486,1.8,5.5,0.332,2.6,3.4,0.760,0.6,3.2,3.8,6.2,2.3,1.2,0.3,2.3,18.6,2026,36.0,"PG,SG"
88,Chet Holmgren,OKC,24.0,69,28.9,6.3,11.3,0.557,1.3,3.5,0.362,3.3,4.1,0.792,1.9,7.0,8.9,1.7,1.6,0.6,1.9,2.3,17.1,2026,38.0,"PF,C"
145,Desmond Bane,ORL,28.0,82,33.6,7.1,14.7,0.484,2.0,5.2,0.391,3.8,4.2,0.908,1.2,2.9,4.1,4.1,2.0,1.0,0.5,3.1,20.1,2026,41.0,"SG,SF"
178,Franz Wagner,ORL,24.0,34,30.0,7.2,14.9,0.481,1.4,4.1,0.345,4.8,5.8,0.823,1.3,3.9,5.2,3.3,1.7,0.9,0.3,2.1,20.6,2026,43.0,"PF,SF"
279,Joel Embiid,PHI,32.0,38,31.6,9.0,18.3,0.489,1.4,4.2,0.333,7.5,8.8,0.854,2.0,5.7,7.7,3.9,2.9,0.6,1.2,2.2,26.9,2026,45.0,C
37,Austin Reaves,LAL,28.0,51,34.5,7.3,14.9,0.490,2.3,6.4,0.360,6.3,7.3,0.871,0.6,4.1,4.7,5.5,3.0,1.1,0.4,2.2,23.3,2026,46.0,"PG,SF,SG"
144,Derrick White,BOS,31.0,77,34.1,5.7,14.4,0.394,2.7,8.3,0.327,2.4,2.6,0.902,1.1,3.3,4.4,5.4,1.7,1.1,1.3,1.5,16.5,2026,47.0,"PG,SG"
301,Josh Hart,NYK,31.0,66,30.2,4.6,9.0,0.508,1.5,3.7,0.413,1.4,1.9,0.720,1.4,6.0,7.4,4.8,1.9,1.1,0.3,2.5,12.0,2026,48.0,"SF,SG"
169,Dyson Daniels,ATL,23.0,76,33.2,5.3,10.2,0.517,0.3,1.5,0.188,1.0,1.6,0.615,2.4,4.4,6.8,5.9,1.8,2.0,0.4,2.2,11.9,2026,49.0,"PG,SF,SG"
98,Coby White,CHA,26.0,50,25.0,5.6,12.5,0.446,2.3,6.4,0.362,3.9,4.8,0.817,0.3,3.1,3.4,4.0,2.6,0.5,0.1,2.2,17.4,2026,50.0,"PG,SG"
399,Michael Porter Jr.,BKN,28.0,52,32.5,8.5,18.4,0.463,3.4,9.3,0.363,3.8,4.4,0.859,1.3,5.7,7.1,3.0,2.3,1.1,0.3,2.2,24.2,2026,51.0,"SF,PF"
139,Deni Avdija,POR,25.0,66,33.3,7.5,16.1,0.462,1.9,6.0,0.318,7.4,9.2,0.802,1.1,5.8,6.9,6.7,3.8,0.8,0.6,2.5,24.2,2026,52.0,"PF,SF,SG"
253,Jarrett Allen,CLE,28.0,56,27.1,6.0,9.4,0.638,0.0,0.2,0.100,3.3,4.7,0.709,2.6,5.9,8.5,1.8,1.3,1.0,0.8,1.7,15.4,2026,53.0,C
232,Jalen Duren,DET,22.0,70,28.2,7.5,11.5,0.650,0.0,0.0,0.000,4.6,6.1,0.747,3.8,6.7,10.5,2.0,1.9,0.8,0.8,2.8,19.5,2026,54.0,C
400,Mikal Bridges,NYK,29.0,82,32.8,5.8,11.7,0.490,1.9,5.1,0.371,1.0,1.2,0.827,1.0,2.8,3.8,3.7,1.0,1.3,0.8,2.0,14.4,2026,56.0,"PF,SF,SG"
440,OG Anunoby,NYK,28.0,67,33.2,5.8,12.0,0.484,2.3,6.1,0.386,2.7,3.3,0.828,1.3,4.0,5.2,2.2,1.8,1.6,0.7,2.4,16.7,2026,57.0,"SF,PF"
415,Myles Turner,MIL,30.0,71,26.9,4.0,9.1,0.440,2.1,5.4,0.383,1.8,2.5,0.740,1.1,4.3,5.3,1.5,1.2,0.7,1.6,2.6,11.9,2026,60.0,C
510,Stephon Castle,SAS,21.0,68,30.0,5.7,12.0,0.471,1.2,3.6,0.332,4.1,5.6,0.734,1.4,3.9,5.3,7.4,3.2,1.1,0.3,3.3,16.7,2026,62.0,"PG,SG"
275,Jimmy Butler III,GSW,36.0,38,31.1,6.3,12.2,0.519,0.8,2.2,0.376,6.5,7.6,0.864,2.3,3.2,5.6,4.9,1.6,1.4,0.2,1.2,20.0,2026,67.0,"PF,SF,SG"
483,Rudy Gobert,MIN,34.0,76,31.3,4.4,6.5,0.682,0.0,0.1,0.000,2.1,4.0,0.526,3.9,7.5,11.5,1.7,1.4,0.8,1.6,2.6,10.9,2026,70.0,C
577,Zach LaVine,SAC,31.0,39,31.4,6.7,14.0,0.479,2.5,6.5,0.390,3.2,3.6,0.880,0.2,2.6,2.8,2.3,1.9,0.7,0.3,2.1,19.2,2026,72.0,"PG,SF,SG"
125,Darius Garland,LAC,26.0,45,29.9,6.9,14.9,0.460,2.7,6.8,0.396,2.3,2.7,0.861,0.4,2.0,2.4,6.7,2.9,1.0,0.2,1.9,18.8,2026,73.0,PG

In [67]:
df.sort_values(by='ADP', inplace=True)
df.head(50)

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
501,Shai Gilgeous-Alexander,OKC,27.0,68,33.2,10.8,19.4,0.553,1.7,4.4,0.386,7.9,9.0,0.879,0.6,3.7,4.3,6.6,2.2,1.4,0.8,2.0,31.1,2026,2.0,PG
559,Victor Wembanyama,SAS,22.0,64,29.2,8.6,16.9,0.512,1.9,5.5,0.349,5.8,7.0,0.827,2.0,9.5,11.5,3.1,2.4,1.0,3.1,2.4,25.0,2026,3.0,C
31,Anthony Edwards,MIN,24.0,61,35.0,9.9,20.2,0.489,3.4,8.4,0.399,5.7,7.2,0.796,0.6,4.4,5.0,3.7,2.9,1.4,0.8,1.9,28.8,2026,6.0,"PG,SF,SG"
71,Cade Cunningham,DET,24.0,64,33.9,8.6,18.6,0.461,2.0,5.7,0.342,4.8,6.0,0.812,0.9,4.7,5.5,9.9,3.7,1.4,0.8,3.1,23.9,2026,7.0,"PG,SG"
266,Jayson Tatum,BOS,28.0,16,32.6,7.4,17.9,0.411,2.9,8.9,0.329,4.1,4.9,0.823,0.5,9.5,10.0,5.3,2.4,1.4,0.2,1.6,21.8,2026,8.0,"SF,PF"
30,Anthony Davis,WAS,33.0,20,31.3,8.5,16.7,0.506,0.5,1.9,0.270,3.0,4.1,0.728,3.1,8.0,11.1,2.8,2.1,1.1,1.7,2.1,20.4,2026,9.0,"PF,C"
317,Karl-Anthony Towns,NYK,30.0,75,31.0,6.9,13.8,0.501,1.5,4.1,0.368,4.8,5.5,0.858,3.1,8.7,11.9,3.0,2.5,0.9,0.5,3.4,20.1,2026,11.0,"PF,C"
245,James Harden,CLE,36.0,70,34.8,7.0,16.0,0.434,3.1,8.2,0.375,6.6,7.5,0.884,0.6,4.2,4.8,8.0,3.5,1.1,0.4,2.0,23.6,2026,12.0,"PG,SG"
554,Tyrese Maxey,PHI,25.0,70,38.0,9.9,21.4,0.462,3.1,8.6,0.367,5.3,6.0,0.892,0.3,3.8,4.1,6.6,2.4,1.9,0.8,2.2,28.3,2026,13.0,"PG,SG"
151,Domantas Sabonis,SAC,30.0,19,29.7,6.3,11.6,0.543,0.3,1.4,0.185,2.9,4.1,0.727,3.4,8.0,11.4,4.1,2.7,0.9,0.2,3.5,15.8,2026,15.0,"C,PF"
21,Amen Thompson,HOU,23.0,79,37.4,7.1,13.2,0.534,0.3,1.5,0.216,3.8,4.9,0.779,3.0,4.8,7.8,5.3,2.4,1.5,0.6,2.2,18.3,2026,16.0,"PG,SF,SG"
509,Stephen Curry,GSW,38.0,43,30.9,8.7,18.6,0.468,4.4,11.3,0.393,4.7,5.1,0.923,0.4,3.2,3.6,4.7,2.8,1.1,0.4,1.7,26.6,2026,18.0,PG
231,Jalen Brunson,NYK,29.0,74,35.0,9.3,19.9,0.467,2.6,7.1,0.369,4.8,5.7,0.841,0.4,2.9,3.3,6.8,2.4,0.8,0.1,2.3,26.0,2026,19.0,PG
531,Trae Young,WAS,27.0,15,25.6,5.4,11.8,0.458,1.8,5.3,0.338,5.3,6.5,0.825,0.3,1.7,2.0,8.0,2.6,0.9,0.1,2.2,17.9,2026,20.0,PG
154,Donovan Mitchell,CLE,29.0,70,33.5,9.7,20.0,0.483,3.2,8.8,0.364,5.3,6.1,0.865,0.7,3.8,4.5,5.7,2.8,1.5,0.3,2.3,27.9,2026,21.0,"PG,SG"
455,Pascal Siakam,IND,32.0,62,33.2,9.0,18.6,0.484,1.7,4.7,0.358,4.2,6.1,0.693,1.4,5.2,6.6,3.8,2.2,1.1,0.4,2.4,24.0,2026,22.0,"C,PF,SF"
107,Cooper Flagg,DAL,19.0,70,33.5,8.0,17.1,0.468,1.0,3.5,0.295,4.0,4.9,0.827,1.2,5.4,6.7,4.5,2.3,1.2,0.9,2.0,21.0,2026,23.0,"PF,SF,SG"
333,Kevin Durant,HOU,37.0,78,36.4,9.2,17.6,0.520,2.4,5.8,0.413,5.2,6.0,0.874,0.5,4.9,5.5,4.8,3.2,0.8,0.9,1.8,26.0,2026,24.0,"PF,SF,SG"
496,Scottie Barnes,TOR,24.0,80,33.5,7.1,14.0,0.507,0.9,2.8,0.304,3.0,3.7,0.815,1.9,5.6,7.5,5.9,2.6,1.4,1.5,2.6,18.1,2026,25.0,"C,PF,SF,SG"
39,Bam Adebayo,MIA,28.0,73,32.4,6.9,15.7,0.442,1.7,5.5,0.318,4.5,5.8,0.778,2.0,8.0,10.0,3.2,1.6,1.2,0.7,1.7,20.1,2026,26.0,"C,PF"
299,Josh Giddey,CHI,23.0,54,32.1,5.9,13.3,0.448,1.9,5.2,0.364,3.2,4.2,0.763,1.2,7.1,8.3,9.1,3.6,1.0,0.5,1.7,17.0,2026,27.0,"PG,SG,SF"
239,Jalen Williams,OKC,25.0,33,28.4,6.5,13.5,0.484,0.7,2.3,0.299,3.3,3.9,0.837,0.8,3.8,4.6,5.5,1.9,1.2,0.3,2.0,17.1,2026,28.0,"PF,SF,SG"
19,Alperen Sengun,HOU,23.0,72,33.3,8.1,15.6,0.519,0.6,1.8,0.305,3.6,5.2,0.691,3.0,5.9,8.9,6.2,3.2,1.2,1.1,3.3,20.4,2026,30.0,"C,PF"
177,Evan Mobley,CLE,25.0,65,31.9,7.2,13.2,0.546,1.0,3.2,0.297,2.8,4.6,0.606,2.4,6.6,9.0,3.6,1.9,0.7,1.7,2.4,18.2,2026,31.0,"PF,C"
234,Jalen Johnson,ATL,24.0,72,35.2,8.3,17.1,0.489,1.7,4.7,0.352,4.2,5.3,0.788,1.4,8.9,10.3,7.9,3.4,1.2,0.4,2.1,22.5,2026,32.0,"PF,SF"
242,Jamal Murray,DEN,29.0,75,35.4,8.8,18.1,0.483,3.3,7.5,0.435,4.6,5.2,0.887,0.4,4.0,4.4,7.1,2.3,0.9,0.4,1.7,25.4,2026,33.0,PG
454,Paolo Banchero,ORL,23.0,72,34.7,7.3,16.0,0.459,1.2,3.8,0.305,6.3,8.2,0.775,1.2,7.2,8.4,5.2,3.1,0.7,0.6,2.0,22.2,2026,34.0,"PF,SF"
214,Ivica Zubac,IND,29.0,48,30.1,6.0,10.0,0.598,0.0,0.0,0.000,2.1,3.0,0.711,3.4,7.2,10.6,2.2,1.8,0.4,0.8,2.3,14.1,2026,35.0,C
130,De'Aaron Fox,SAS,28.0,72,31.0,7.1,14.5,0.486,1.8,5.5,0.332,2.6,3.4,0.760,0.6,3.2,3.8,6.2,2.3,1.2,0.3,2.3,18.6,2026,36.0,"PG,SG"
88,Chet Holmgren,OKC,24.0,69,28.9,6.3,11.3,0.557,1.3,3.5,0.362,3.3,4.1,0.792,1.9,7.0,8.9,1.7,1.6,0.6,1.9,2.3,17.1,2026,38.0,"PF,C"
145,Desmond Bane,ORL,28.0,82,33.6,7.1,14.7,0.484,2.0,5.2,0.391,3.8,4.2,0.908,1.2,2.9,4.1,4.1,2.0,1.0,0.5,3.1,20.1,2026,41.0,"SG,SF"
178,Franz Wagner,ORL,24.0,34,30.0,7.2,14.9,0.481,1.4,4.1,0.345,4.8,5.8,0.823,1.3,3.9,5.2,3.3,1.7,0.9,0.3,2.1,20.6,2026,43.0,"PF,SF"
279,Joel Embiid,PHI,32.0,38,31.6,9.0,18.3,0.489,1.4,4.2,0.333,7.5,8.8,0.854,2.0,5.7,7.7,3.9,2.9,0.6,1.2,2.2,26.9,2026,45.0,C
37,Austin Reaves,LAL,28.0,51,34.5,7.3,14.9,0.490,2.3,6.4,0.360,6.3,7.3,0.871,0.6,4.1,4.7,5.5,3.0,1.1,0.4,2.2,23.3,2026,46.0,"PG,SF,SG"
144,Derrick White,BOS,31.0,77,34.1,5.7,14.4,0.394,2.7,8.3,0.327,2.4,2.6,0.902,1.1,3.3,4.4,5.4,1.7,1.1,1.3,1.5,16.5,2026,47.0,"PG,SG"
301,Josh Hart,NYK,31.0,66,30.2,4.6,9.0,0.508,1.5,3.7,0.413,1.4,1.9,0.720,1.4,6.0,7.4,4.8,1.9,1.1,0.3,2.5,12.0,2026,48.0,"SF,SG"
169,Dyson Daniels,ATL,23.0,76,33.2,5.3,10.2,0.517,0.3,1.5,0.188,1.0,1.6,0.615,2.4,4.4,6.8,5.9,1.8,2.0,0.4,2.2,11.9,2026,49.0,"PG,SF,SG"
98,Coby White,CHA,26.0,50,25.0,5.6,12.5,0.446,2.3,6.4,0.362,3.9,4.8,0.817,0.3,3.1,3.4,4.0,2.6,0.5,0.1,2.2,17.4,2026,50.0,"PG,SG"
399,Michael Porter Jr.,BKN,28.0,52,32.5,8.5,18.4,0.463,3.4,9.3,0.363,3.8,4.4,0.859,1.3,5.7,7.1,3.0,2.3,1.1,0.3,2.2,24.2,2026,51.0,"SF,PF"
139,Deni Avdija,POR,25.0,66,33.3,7.5,16.1,0.462,1.9,6.0,0.318,7.4,9.2,0.802,1.1,5.8,6.9,6.7,3.8,0.8,0.6,2.5,24.2,2026,52.0,"PF,SF,SG"
253,Jarrett Allen,CLE,28.0,56,27.1,6.0,9.4,0.638,0.0,0.2,0.100,3.3,4.7,0.709,2.6,5.9,8.5,1.8,1.3,1.0,0.8,1.7,15.4,2026,53.0,C
232,Jalen Duren,DET,22.0,70,28.2,7.5,11.5,0.650,0.0,0.0,0.000,4.6,6.1,0.747,3.8,6.7,10.5,2.0,1.9,0.8,0.8,2.8,19.5,2026,54.0,C
400,Mikal Bridges,NYK,29.0,82,32.8,5.8,11.7,0.490,1.9,5.1,0.371,1.0,1.2,0.827,1.0,2.8,3.8,3.7,1.0,1.3,0.8,2.0,14.4,2026,56.0,"PF,SF,SG"
440,OG Anunoby,NYK,28.0,67,33.2,5.8,12.0,0.484,2.3,6.1,0.386,2.7,3.3,0.828,1.3,4.0,5.2,2.2,1.8,1.6,0.7,2.4,16.7,2026,57.0,"SF,PF"
415,Myles Turner,MIL,30.0,71,26.9,4.0,9.1,0.440,2.1,5.4,0.383,1.8,2.5,0.740,1.1,4.3,5.3,1.5,1.2,0.7,1.6,2.6,11.9,2026,60.0,C
510,Stephon Castle,SAS,21.0,68,30.0,5.7,12.0,0.471,1.2,3.6,0.332,4.1,5.6,0.734,1.4,3.9,5.3,7.4,3.2,1.1,0.3,3.3,16.7,2026,62.0,"PG,SG"
275,Jimmy Butler III,GSW,36.0,38,31.1,6.3,12.2,0.519,0.8,2.2,0.376,6.5,7.6,0.864,2.3,3.2,5.6,4.9,1.6,1.4,0.2,1.2,20.0,2026,67.0,"PF,SF,SG"
483,Rudy Gobert,MIN,34.0,76,31.3,4.4,6.5,0.682,0.0,0.1,0.000,2.1,4.0,0.526,3.9,7.5,11.5,1.7,1.4,0.8,1.6,2.6,10.9,2026,70.0,C
577,Zach LaVine,SAC,31.0,39,31.4,6.7,14.0,0.479,2.5,6.5,0.390,3.2,3.6,0.880,0.2,2.6,2.8,2.3,1.9,0.7,0.3,2.1,19.2,2026,72.0,"PG,SF,SG"
125,Darius Garland,LAC,26.0,45,29.9,6.9,14.9,0.460,2.7,6.8,0.396,2.3,2.7,0.861,0.4,2.0,2.4,6.7,2.9,1.0,0.2,1.9,18.8,2026,73.0,PG